// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/replicatedcom/ship/pkg/lifecycle/render/config (interfaces: Resolver)

// Package config is a generated GoMock package.
package config

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	api "github.com/replicatedcom/ship/pkg/api"
	reflect "reflect"
)

// MockResolver is a mock of Resolver interface
type MockResolver struct {
	ctrl     *gomock.Controller
	recorder *MockResolverMockRecorder
}

// MockResolverMockRecorder is the mock recorder for MockResolver
type MockResolverMockRecorder struct {
	mock *MockResolver
}

// NewMockResolver creates a new mock instance
func NewMockResolver(ctrl *gomock.Controller) *MockResolver {
	mock := &MockResolver{ctrl: ctrl}
	mock.recorder = &MockResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockResolver) EXPECT() *MockResolverMockRecorder {
	return m.recorder
}

// ResolveConfig mocks base method
func (m *MockResolver) ResolveConfig(arg0 context.Context, arg1 *api.ReleaseMetadata, arg2 map[string]interface{}) (map[string]interface{}, error) {
	ret := m.ctrl.Call(m, "ResolveConfig", arg0, arg1, arg2)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveConfig indicates an expected call of ResolveConfig
func (mr *MockResolverMockRecorder) ResolveConfig(arg0, arg1, arg2 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveConfig", reflect.TypeOf((*MockResolver)(nil).ResolveConfig), arg0, arg1, arg2)
}
