FROM debian:stretch-slim

RUN apt-get update -y && \
    apt-get install -y ca-certificates && \
	rm -rf /var/lib/apt/lists/*

EXPOSE 3000

ARG version=unknown
ENV VERSION=$version

ADD bin/ship /usr/local/bin/ship

CMD ["/usr/local/bin/ship", "serve"]