FROM golang:1.13

RUN cd /opt && curl -LO https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.81.0/pact-1.81.0-linux-x86_64.tar.gz && tar xzf pact-1.81.0-linux-x86_64.tar.gz
ENV PATH="/opt/pact/bin:${PATH}"
ENV GO111MODULE=on

WORKDIR /go/src/github.com/replicatedhq/ship

ADD . .
